image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 14 x64
  - npm ci

build_script:
  - npm run electron:build

test: off
